[package]
name = "tutorials"
authors = ["Michael de Silva <michael@inertialbox.com>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "3", features = ["derive"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.16"

[dev-dependencies]
test-log = "0.2.10"
